### ISSUE TITLE
Fail to subscribe with Name box hidden due to IsSet(Name) returning false.

### ISSUE THREAD

**Issue by tomlooman** [mauryaratan/embed-sendy#20]
Since I updated around Februari the subscribe form fails when the form has no Name parameter visible for users due to the **process_sendy()** function returning "error: invalid parameters" due to the check on **line 513: isset('name')** returning false.

If I enable the name box but don't fill in a name, it's still fine because the param will be send as '[No Name]' it seems.

Removing that statement "fixed" it for me, can you please fix this in a way you think it best suited for the code. it silently stopped working for months and only just found out thanks to random test.

**Comment by mauryaratan** [comment]
Thanks @tomlooman. Fixed in 74fea492e351cdba7c33c7657dedd43106f55a62.
